Clean up error

diff --git a/config/nnn/plugins/cd b/config/nnn/plugins/cd
--- a/config/nnn/plugins/cd
+++ b/config/nnn/plugins/cd
@@ -15,10 +15,8 @@ IFS= read -r line
 result="$line"
 eval result="$(printf "%q" "$line")"
 
-echo "result = $result"
-
 if [ ! -d "$result" ]; then
-  # Show error
+  echo "Error: $result is not a valid directory" >&2
   read -r _
   exit 1
 fi
