Sync snippets

diff --git a/emacs.d/snippets/sh-mode/echo_err b/emacs.d/snippets/sh-mode/echo_err
--- a/emacs.d/snippets/sh-mode/echo_err
+++ b/emacs.d/snippets/sh-mode/echo_err
@@ -1,5 +1,5 @@
 # -*- mode: snippet -*-
-# key: echo_error
+# key: echo_err
 # name: Echo to standard error
 # --
-echo "${0:Error}" >&2
+echo "${1:Error}" >&2
