Improve snippets

diff --git a/emacs.d/snippets/sh-mode/getopts b/emacs.d/snippets/sh-mode/getopts
--- a/emacs.d/snippets/sh-mode/getopts
+++ b/emacs.d/snippets/sh-mode/getopts
@@ -16,11 +16,11 @@ while getopts ":p:fh" option; do
       exit 0
       ;;
     :)
-      echo "Option -$OPTARG requires an argument" >&2
+      echo "Option -\$OPTARG requires an argument" >&2
       exit 1
       ;;
     \?)
-      echo "Invalid option: -$OPTARG" >&2
+      echo "Invalid option: -\$OPTARG" >&2
       exit 1
       ;;
   esac
