Update snippet stops

diff --git a/emacs.d/snippets/sh-mode/rk_echo_err b/emacs.d/snippets/sh-mode/rk_echo_err
--- a/emacs.d/snippets/sh-mode/rk_echo_err
+++ b/emacs.d/snippets/sh-mode/rk_echo_err
@@ -2,4 +2,4 @@
 # key: rk_echo_err
 # name: Echo to standard error
 # --
-echo "${0:Error}" >&2
+echo "${1:Error}" >&2
